POST http://localhost:3001/api/bloglist/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYyMDAxYTZmMDA5YjMzYzNiZjBkOWMzZSIsImlhdCI6MTY0NDQwNzk0MCwiZXhwIjoxNjQ0NDExNTQwfQ.yb9DVps2Gc74lIh4_xeFsjdNWixCV7BvT7L8-mpIoAo

{
    "author": "santi argento 5",
    "title": "blog c",
    "url": "bacing",
    "likes":22,
    "userId": "62001a6f009b33c3bf0d9c3e"
}