POST http://localhost:3003/api/bloglist/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYyMWZmZjVmZDM3MTE5Y2JiYjdhMzViOCIsImlhdCI6MTY0NjI2NDM0NSwiZXhwIjoxNjQ2MjY3OTQ1fQ.00pjiuZWMgQQVJorgZ3OQVZsyIsunSU_pQjcSKzfKko

{
    "author": "santi argento 5",
    "title": "blog c",
    "url": "bacing",
    "likes":22,
    "userId": "621fff5fd37119cbbb7a35b8"
}